{% set version = "2.7.0" %}

package:
  name: python-blosc2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blosc2/blosc2-{{ version }}.tar.gz
  sha256: 9b982c1d40560eefb4a01d67c57e786d39a5ee9696f3deadd32ebf5f8885eb2a

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - make                                # [unix]
    - ninja
    - pkg-config
  host:
    - c-blosc2
    - cython
    - numpy
    - pathlib
    - python
    - python-build
    - scikit-build
    - setuptools
  run:
    - python
    - msgpack-python
    - ndindex >=1.4
    - py-cpuinfo
    - numexpr

test:
  imports:
    - blosc2
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/blosc2
  summary: A Python wrapper for the extremely fast Blosc2 compression library
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  dev_url: https://github.com/Blosc/python-blosc2

extra:
  recipe-maintainers:
    - FrancescAlted
    - goanpeca
    - martaiborra
