{% set base_name = "blosc2" %}
{% set name = "python-blosc2" %}
{% set version = "2.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ base_name[0] }}/{{ base_name }}/{{ base_name }}-{{ version }}.tar.gz
  sha256: 63606498aaa72d58215b618d4512d5d3de29000a7b01a870edce8cb21d237c40
  patches:
    # Delete after https://github.com/Blosc/python-blosc2/pull/148 is merged
    - 0001-Add-imported-target-with-pkg-config-to-support-windo.patch

build:
  number: 1
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - c-blosc2
    - cmake
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - make                                # [unix]
    - ninja
    - pkg-config
    - python                              # [build_platform != target_platform]
  host:
    - c-blosc2
    - cython >=3
    - numpy >=1.20.3
    - pathlib
    - python
    - python-build
    - scikit-build
    - setuptools
  run:
    - msgpack-python
    - ndindex >=1.4
    - {{ pin_compatible('numpy') }}
    - py-cpuinfo
    - python

test:
  imports:
    - blosc2
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/blosc2
  summary: A Python wrapper for the extremely fast Blosc2 compression library
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  dev_url: https://github.com/Blosc/python-blosc2

extra:
  recipe-maintainers:
    - FrancescAlted
    - goanpeca
    - martaiborra
